Idp 3
munHunger/idp pull request #2
Opened 2018-02-10 13:35 UTC by Oceantalks

2018-02-11 11:20 UTC, munHunger requested changes
Långt ifrån klart.
Vart är hanteringen av klienten?

2018-02-11 11:20 UTC, munHunger commented on src/main/java/se/munhunger/idp/rest/User.java
> +            return Response.status(Response.Status.BAD_REQUEST)
404 Känns rimligare

2018-02-11 11:20 UTC, munHunger commented on src/main/java/se/munhunger/idp/rest/User.java
> +            return Response.status(Response.Status.EXPECTATION_FAILED)
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/417
nope.
Det är snarare bad request

2018-02-11 11:20 UTC, munHunger commented on src/main/java/se/munhunger/idp/model/persistant/Client.java
> +    private String creationdate;
Borde det verkligen vara en sträng och inte en Date?
Om det är en sträng så måste den valideras

2018-02-12 09:28 UTC, munHunger commented on src/main/java/se/munhunger/idp/dao/ClientDAO.java
> +            Optional.ofNullable(getClient(client.getName())).orElseThrow(NotInDatabaseException::new);
Kommer aldrig kasta NotInDatabaseException.
Vad som skulle trigga detta är en tom optional.
ofNullable skapar en tom optional om objektet är null.
getClient kommer ALLTID returnera en optional som då aldrig kan vara null

2018-02-12 09:30 UTC, munHunger commented on src/main/java/se/munhunger/idp/services/ClientService.java
> +        clientDAO.updateClient(client);
Tror att jag kan ändra creationdate här. det känns inte helt OK

2018-02-12 10:46 UTC, Oceantalks commented on src/main/java/se/munhunger/idp/services/ClientService.java
> +        clientDAO.updateClient(client);
Den låg på create metoden men har ändrat så att hibernate sätter datumet i fortsättingen

2018-02-12 12:59 UTC, munHunger requested changes

2018-02-12 12:59 UTC, munHunger commented on src/main/java/se/munhunger/idp/services/ClientService.java
> +        clientDAO.createClient(client);
Kan numer sätta datum till vad jag vill.

2018-02-13 08:42 UTC, munHunger commented on src/main/java/se/munhunger/idp/model/persistant/Client.java
> +
2 tomma rader! ta bort

2018-02-13 17:00 UTC, munHunger requested changes

2018-02-13 17:00 UTC, munHunger commented on src/main/java/se/munhunger/idp/exception/ClientNotInDatabaseException.java
> +public class ClientNotInDatabaseException extends Exception{
rimligare att extenda NotInDatabaseException, men OK

2018-02-14 09:10 UTC, Oceantalks commented on src/main/java/se/munhunger/idp/services/ClientService.java
> +        clientDAO.createClient(client);
Du kommer inte se någon ändring på denna klassen utan på Client klassen där jag har gjort en annotations ändring så att datumet inte sätts från json creationDate utan hibernate oavsett vad som följer med

2018-02-15 06:18 UTC, munHunger approved these changes

2018-02-15 06:18 UTC, merged