Idp link user to client
munHunger/idp pull request #3
Opened 2018-02-14 09:36 UTC by Oceantalks

Denna branchen är en branchning av IDP-3 med länkning mellan user och client

2018-02-14 09:52 UTC, munHunger requested changes

2018-02-14 09:52 UTC, munHunger commented on src/main/java/se/munhunger/idp/model/persistant/Client.java
> +public class Client {
Klienten bör ha en relation till user

2018-02-14 09:52 UTC, munHunger commented on src/main/java/se/munhunger/idp/model/persistant/User.java
> +    public User(String username, String hashPassword, String firstname, String lastname, String email, List<Client> clients) {
Ta bort listan på klienter.
Det bör vara ett krav på en klient att ha en skapad av användare, vilket skapar ett onödigt cirkulärt beroende om du har den i konstruktorn

2018-02-14 09:52 UTC, munHunger commented on src/main/java/se/munhunger/idp/rest/Client.java
> +        } catch (EmailNotValidException e) {
Borde aldrig få det här problemet då inte uppdaterar mail addressen på användaren och en förutsättning är såklart att användaren redan är sparad med giltig mail

2018-02-14 09:52 UTC, munHunger commented on src/main/java/se/munhunger/idp/rest/Client.java
> +        } catch (NoSuchAlgorithmException e) {
Borde inte få det här heller.
Om du får det ändå så bör du fånga upp det i service lagret

2018-02-14 09:52 UTC, munHunger commented on src/main/java/se/munhunger/idp/services/ClientService.java
> +        user.setClients(clientList);
det här är redundant.
du har aldrig ändrat på clientList pekaren så därför behöver du inte ändra referensen hos usern

2018-02-14 09:52 UTC, munHunger commented on src/main/java/se/munhunger/idp/services/UserService.java
>          userDAO.deleteUser(username);
Bör validera att användaren inte har några klienter för att undvika orphaned klienter

2018-02-15 17:13 UTC, munHunger requested changes

2018-02-15 17:13 UTC, munHunger commented on src/main/java/se/munhunger/idp/rest/Client.java
> +    public Response deleteUser(@PathParam("clientname") String clientname,@PathParam("username") String username) {
Varför har du delete user i client?

2018-02-15 17:13 UTC, munHunger commented on src/main/java/se/munhunger/idp/rest/Client.java
> +    @Path("/{clientname}/{username}")
rimligare att ha detta som en query paramater då du snarare jobbar med klienten än användaren kopplad till klienten

2018-02-15 17:13 UTC, munHunger commented on src/main/java/se/munhunger/idp/rest/Client.java
> +        } catch (EmailNotValidException e) {
Det enda som borde slängas här är NotInDatabaseExceptions.
och ge fan i e.printStackTrace!

2018-02-15 17:13 UTC, munHunger commented on src/main/java/se/munhunger/idp/services/ClientService.java
> +        //clientDAO.createClient(client);
nej!

2018-02-15 17:13 UTC, munHunger commented on src/main/java/se/munhunger/idp/services/ClientService.java
> +        for (Client tempClient: oldList) {
Den här lösningen är inte alls acceptabel!
speciellt då det finns en delete funktion på listor

2018-02-15 17:13 UTC, munHunger commented on src/main/java/se/munhunger/idp/services/ClientService.java
> +        //clientDAO.deleteClient(clientname);
nej!!

2018-02-16 06:47 UTC, munHunger commented on src/main/java/se/munhunger/idp/services/ClientService.java
> +        //clientDAO.createClient(client);
ge fan

2018-02-16 06:49 UTC, munHunger commented on src/main/java/se/munhunger/idp/rest/Client.java
> +    public Response deleteUser(@PathParam("clientname") String clientname,@PathParam("username") String username) {
fix

2018-02-16 07:45 UTC, Oceantalks commented on src/main/java/se/munhunger/idp/model/persistant/Client.java
> +public class Client {
Jag vet, men jag försöker skapa en bidirectional relation så får jag too many recursions problem... där av har jag skippat det. Prova gärna köra koden med en bidirectional så att du också får se problemen.....

2018-02-16 08:24 UTC, Oceantalks commented on src/main/java/se/munhunger/idp/rest/Client.java
> +        } catch (EmailNotValidException e) {
I och med att jag anropar User CRUD operationerna för att skapa en koppling för clienten då vi inte har en bidirectional koppling så kan jag få denna Exception. Vill du att jag gör på något annat sätt hojta gärna

2018-02-16 11:40 UTC, munHunger requested changes

2018-02-16 11:40 UTC, munHunger commented on src/main/java/se/munhunger/idp/exception/ClientNotInDatabaseException.java
> +    public ClientNotInDatabaseException(String message) {
det här finns väl redan i Exception?
tror att den har ett message fält

2018-02-16 11:40 UTC, munHunger commented on src/main/java/se/munhunger/idp/rest/Client.java
> +        } catch (Exception e) {
Vad händer om det är en NPE, SQLException, IOException osv...?
det är väldigt farligt att fånga allt såhär

2018-02-16 11:40 UTC, munHunger commented on src/main/java/se/munhunger/idp/rest/Client.java
>              return Response.status(Response.Status.NOT_FOUND)
fel statuskod

2018-02-16 11:40 UTC, munHunger commented on src/main/java/se/munhunger/idp/services/ClientService.java
> +        User user = null;
Varför deklarerar du user här uppe?

2018-02-16 11:40 UTC, munHunger commented on src/main/java/se/munhunger/idp/services/ClientService.java
> +    public void createClient(Client client, String username) throws Exception {
Farligt att slänga för generiska exceptions!

2018-02-16 13:19 UTC, munHunger commented on src/main/java/se/munhunger/idp/rest/Client.java
> +        } catch (EmailNotValidException e) {
I det här fallet där du vet att det aldrig kan tänkas hända så är det rimligare att inte kasta det vidare ifrån servicen. så här kan det vara rimligt att typ lägga ut en severe loggning

2018-02-16 13:21 UTC, munHunger requested changes

2018-02-16 13:21 UTC, munHunger commented on src/main/java/se/munhunger/idp/rest/Client.java
> +            return Response.status(Response.Status.NOT_FOUND)
fel felkod

2018-02-16 13:21 UTC, munHunger commented on src/main/java/se/munhunger/idp/rest/Client.java
> +            return Response.status(Response.Status.NOT_FOUND)
fel felkod

2018-02-16 13:21 UTC, munHunger commented on src/main/java/se/munhunger/idp/rest/Client.java
> +            return Response.status(Response.Status.NOT_FOUND)
fel felkod

2018-02-16 13:21 UTC, munHunger commented on src/main/java/se/munhunger/idp/rest/User.java
> +            return Response.status(Response.Status.NOT_FOUND)
fel felkod

2018-02-20 15:30 UTC, closed without merging