Idp logging
munHunger/idp pull request #9
Opened 2018-02-19 16:10 UTC by Oceantalks

Now Logging all operations i IDP, with no merge conflicts, with Jenkins and Docker back

2018-02-19 19:47 UTC, munHunger requested changes

2018-02-19 19:47 UTC, munHunger commented on src/main/java/se/munhunger/idp/dao/ClientDAO.java
> +    private static java.util.logging.Logger log = java.util.logging.Logger.getLogger(ClientDAO.class.getName());
använd inte hela namnet. importera istället rätt paket och kör bara Logger log = ...

2018-02-19 19:47 UTC, munHunger commented on src/main/java/se/munhunger/idp/dao/UserDAO.java
> +    private static java.util.logging.Logger log = java.util.logging.Logger.getLogger(UserDAO.class.getName());
Importera rätt paket och använd det

2018-02-19 19:47 UTC, munHunger commented on src/main/java/se/munhunger/idp/rest/Client.java
> +    private static java.util.logging.Logger log = java.util.logging.Logger.getLogger(Client.class.getName());
se tidigare kommentarer om samma ämne

2018-02-19 19:47 UTC, munHunger commented on src/main/java/se/munhunger/idp/rest/Client.java
> +    public Response deleteClient(@PathParam("clientname") String clientname,@PathParam("username") String username) {
det här ska gå att göra utan att mata in username

2018-02-19 19:47 UTC, munHunger commented on src/main/java/se/munhunger/idp/rest/User.java
> +            return Response.status(Response.Status.EXPECTATION_FAILED)
nope. läs på om status koderna innan du sätter något arbiträrt. HTTP 417 är inte ens nästan relevant till det här felet

2018-02-19 19:47 UTC, munHunger commented on src/main/java/se/munhunger/idp/rest/User.java
> +            return Response.status(Response.Status.FORBIDDEN)
NOPE

2018-02-19 19:47 UTC, munHunger commented on src/main/java/se/munhunger/idp/services/ClientService.java
> +        User user = null;
onödig deklaration

2018-02-19 19:47 UTC, munHunger commented on src/main/java/se/munhunger/idp/services/UserService.java
> +        if (user.getClients().size() != 0){
kolla mot empty istället

2018-02-20 18:33 UTC, munHunger requested changes

2018-02-20 18:33 UTC, munHunger commented on src/main/java/se/munhunger/idp/dao/UserDAO.java
> +            //List<User> userList = query.getResultList();
Ta bort!

2018-02-20 18:33 UTC, munHunger commented on src/main/java/se/munhunger/idp/rest/Client.java
> +    @Path("/{clientname}/{username}")
Path parametern är inte mappad

2018-02-20 18:33 UTC, munHunger commented on src/main/java/se/munhunger/idp/rest/User.java
> +            return Response.status(Response.Status.BAD_REQUEST)
400 felet pekar på att användaren gjort något fel.
I det här fallet så blev det fel för att servern inte kunde hitta en hashalgoritm, och det finns därmed inget som användaren kan göra åt saken, alltså bör detta vara 500

2018-02-20 18:33 UTC, munHunger commented on src/main/java/se/munhunger/idp/rest/User.java
> +        log.info(() -> "RestService POST createUser called, with object: " + user.toString());
User har ingen egen toString funktion, så denna log gör inget vettigt

2018-02-20 18:33 UTC, munHunger commented on src/main/java/se/munhunger/idp/services/ClientService.java
> +        log.info(() -> "Creating Client: " + client.toString() + " with parent user: " + username);
Client har ingen toString funktion vilket betyder att den här printen är helt meningslös

2018-02-20 18:33 UTC, munHunger commented on src/main/java/se/munhunger/idp/services/ClientService.java
> +        user.setClients(clientList);
redundant anrop

2018-02-20 18:33 UTC, munHunger commented on src/main/java/se/munhunger/idp/services/ClientService.java
> +        for (User user : userList) {
indenteringsfel

2018-02-20 18:33 UTC, munHunger commented on src/main/java/se/munhunger/idp/dao/UserDAO.java
> +    public List<User> findUserByClient(String clientname){
Kan en client någonsin ha mer än 1 creator?
Om den kan så får du fixa så att det inte går.
samt att detta inte borde returnera en lista

2018-02-21 08:46 UTC, Oceantalks commented on src/main/java/se/munhunger/idp/services/ClientService.java
> +        log.info(() -> "Creating Client: " + client.toString() + " with parent user: " + username);
Har ordnat dessa med att skapa toString på både User och Client dessa har inte försvunnit pga att ändringen sker i model klasserna

2018-02-21 08:49 UTC, munHunger requested changes

2018-02-21 08:49 UTC, munHunger commented on src/main/java/se/munhunger/idp/dao/UserDAO.java
> +            return Optional.of(user.get(0));
Vad händer om listan är tom?

2018-02-21 08:49 UTC, munHunger commented on src/main/java/se/munhunger/idp/model/persistant/User.java
> +                ", password='" + password + '\'' +
Har du password här så kommer du i vissa lägen att skriva ut ett ohashat lösenord i loggen.
I andra fall så läcker du "endast" hashade lösenord till loggen

2018-02-21 08:51 UTC, munHunger requested changes

2018-02-21 08:51 UTC, munHunger commented on src/main/java/se/munhunger/idp/dao/UserDAO.java
> +import java.util.ArrayList;
Dessa används inte längre

2018-02-21 08:51 UTC, munHunger commented on src/main/java/se/munhunger/idp/services/UserService.java
> +import java.util.List;
Tror inte att dessa används längre

2018-02-21 08:51 UTC, Oceantalks commented on src/main/java/se/munhunger/idp/model/persistant/User.java
> +                ", password='" + password + '\'' +
ska vi skippa lösenordet helt och håller från toString metoden?

2018-02-21 09:09 UTC, munHunger approved these changes

2018-02-21 14:03 UTC, merged